 spring:
   application:
     name: config-sever
   cloud:
     config:
       server:
         git:
           uri: https://github.com/isuruPrabhath01/config-file-highway-ticketing-api
 server:
   port: 8089